version: '2'

services:
  couchdb:
    image: couchdb
    restart: always

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - couchdb
    restart: always
    environment:
      - DB_DATABASE=hackatum
      - DB_USER=hackatum
      - DB_PASSWORD=test
      - DB_HOST=couchdb
      - DB_PORT=5984
    volumes:
      - './code:/code'
